### ISSUE TITLE
Roll singleton into option of factory/provider

### ISSUE THREAD

**Issue by neverfox** [noder-io/noder.io#1]
Is there a reason that `$singleton` doesn't support DI? It seems to me that this should be possible, in which case, it might make sense to simply do away with an explicit function and allow for making a singleton as an option to `$factory` or `$provider`.

**Comment by Nicolab** [comment]
Hello,

`$provider` and `$factory` are singletons. I will specify this in the doc.
`$singleton` + DI = `$provider`

If necessary, it's possible to appeal to the dependencies in a singleton with [$inject](http://noder.io/api/noder.html#-inject),  [$invoke](http://noder.io/api/noder.html#-invoke), [$apply](http://noder.io/api/noder.html#-apply) or [$di](http://noder.io/api/noder.html#-di)

**Comment by neverfox** [comment]
Ah, I see. Does that suggest that perhaps the name `$singleton` is misleading? For me -- and I imagine, for others -- the name suggests something very different from simply "doesn't have dependencies".

**Comment by Nicolab** [comment]
The name indicates precisely what it is, a [singleton pattern](http://en.wikipedia.org/wiki/Singleton_pattern)

The "factory" builds and instantiates an object (object / service factory) , so here the dependency injection has meaning.

The provider's role is to provide a service, so here too the dependency injection has meaning.

In large applications with several services, it is common to see factories built with  providers injected. For example, many Angular modules work this way.

In Noder, 3 are constructed only once (on the first call) with incremental liability that can be considered like this:
- **singleton**: make only a singleton
- **provider**: provides a service, If necessary it resolves dependencies for providing. When dependencies are resolved, it avoids to resolve and build on every call (built once).
- **factory**: like a provider, except the factory returns the constructed service and called (built and called once).

``` js
noder.$provider('helloProvider', function() {
  return 'hello world ';
});

noder.$factory('helloFactory', function() {
  return 'hello world';
});

noder.$apply(function() {

   // function
   console.log(typeof this.helloProvider);

   // string
   console.log(typeof this.helloFactory);
});
```

This is useful to provide functionalities with single responsibility:

``` js
noder.$provider('helloProvider', function(name) {
  return 'hello ' + name;
});

noder.$factory('helloNeverfox', 'helloProvider', function(hello) {
  return hello('neverfox');
});

noder.$factory('upperNeverfox', 'helloNeverfox', function(neverfox) {
  return neverfox.toUpperCase();
});
```

I hope my explanation is clear, my English is not good.

**Comment by neverfox** [comment]
> The name indicates precisely what it is, a singleton pattern

Sure, but it's not the only method that provides a singleton pattern, as you just clarified, which is why it might be confusing. It's why I originally assumed the others weren't singletons. It's just not clear what use it serves, except as a shortcut for `$factory('foo', [], function () { ... })` (a factory with no dependencies).

**Comment by Nicolab** [comment]
Indeed, I understand the confusion. I must clarify the doc concerning this.

Technical memo:
- singleton: it's the [singleton](http://en.wikipedia.org/wiki/Singleton_pattern) design pattern.
- factory:  it's the [factory](http://en.wikipedia.org/wiki/Factory_method_pattern) design pattern. By definition it is built only once. To build itself, maybe it require some dependencies, it's the same behavior in several frameworks.

**Comment by agibalov** [comment]
Hi @Nicolab ,

I would say that in most cases the user will be confused with your interpretation of these words. In context of IoC containers, the word "singleton" usually refers to the object life cycle: such an object is created only once per context, and all the further requests will resolve to the same instance. The terms "singleton design pattern" and "singleton object" have very few in common. Then, the "factory design pattern" does not make any statements concerning the produced objects life cycle. Moreover, I would expect it to produce new objects again and again. Briefly, you are mixing the scopes and construction approaches. Take look at the terminology used by guice, spring ioc, ninject - it should make things more clear.

**Comment by Nicolab** [comment]
Hi Loki2302,

Yes I have mixed the scopes and construction approaches. Noder was created to serve as a container IoC, usable with key / value.

The methods singleton(), provider() and factory() are three way to store a value in a `Collection` instance.
The factory() method is not an "abstract" factory creator (which returns each time a new factored object) but a "service" factory where each service is stored in the current `Collection` instance. 
A service is built at the first invocation (instance created only once).

Of course it's possible to define a factory function that will create a new object on each call.

Take look at the terminology used by Pimple and Angular.
